### ISSUE TITLE
Specific updates to Cheat Sheet documentation source file

### ISSUE THREAD

**Issue by rjhanes** [NREL/tyche#105]
# Task management info

Relevant branches:
* `sam-edits-2`, for Sam's edits
* `tj-doc-edits` for TJ's edits

These two branches are starting off identical and represent the documentation deployed to GitHub Pages [here](https://nrel.github.io/tyche-docs/index.html).

## Some notes on revising workflow

* **Please do not edit the `doc-updates-fy23q1` branch directly.** This will be where we merge together our individual edits once this round of revisions is done.
* I've assigned myself to several of the to-do items below; feel free to assign me to other items you'd like me to address, and assign yourself to anything you'll be addressing.
* When revising, you can either edit the source files directly and use this issue or your personal notes to keep track of to-do items, or create a pull request into `doc-updates-fy23q1` for easier line-by-line commenting (you'll need to make a small commit first, so the branches aren't identical). If you'd prefer you can also put comments on the PDF documentation  (linked just below) for later implementation. Try to keep meta-notes out of the source files themselves.
[Tyche.pdf](https://github.com/NREL/tyche/files/9688101/Tyche.pdf)
* When you are done with this round of revisions, create a Pull Request merging your personal branch into `doc-updates-fy23q1` and request at least one review.

## Some notes on formatting

* Do not delete any of the cross-references used to refer to Tables and Figures such as the example below. Using these cross-references instead of plaintext "Table X" lets us automatically keep table and figure numbering consistent across all sections of the documentation.
```
:numref:`tbl-designsvars`
```
* Do not delete any of the table/figure headers either, such as the example below. These enable cross-referencing and become captions when the docs are compiled.
```
.. _tbl-designsdict:
.. table:: Data dictionary for the *designs* dataset which defines various technology versions resulting from R&D investments.
```
* When working inside a doc source file, the only header marked with equals signs should be the one at the very top of the file. Headers marked with equals signs go into the main documentation table of contents.

-
- [x] # To do items
- [x] ## On line 205, re the mandatory Variables within the *designs* dataset:
- [x] **I  am unable to create the designs table. These are the questions that I am faced with when creating the designs table that are not being answered by the Cheat sheet**
- [x] -  **I do not have any input output efficiency, lifetime, scale etc. Then should I put it as blank or None** ??
- [x] -  **How to put in irrelevant information or not required information in the different columns**

- [x] ## On line 224, re the *parameters* dataset
- [x] Questions and issues
- [x] - I do not have any parameters What do I do with parameters file
- [x] - I created an empty file and it failed. 

## Variable location, re the technology model (.py) file
- [ ] Move this section further up, close to the section on the Jupyter technology analysis notebook
- [x] <Give that Numpy documentation is quite long (reference is 2000 pages; user manual is 500 pages), this is not very useful.  Need to briefly explain how these stacks are set up, how they are used, and why vectorization is so powerful here.>
    * Response: The link is specifically to `numpy.stack` rather than the entire Numpy documentation. The page explains what a stack is and provides several examples of how to use them; examples are also in the technology models already developed. A discussion on vectorization is better suited to the Approach section.

## On line 329, re the *indices* dataset

ISSUE

- [x] **I  am unable to create the indices table. These are the questions that I am faced with when creating the indices table that are not being answered by the Cheat sheet**
- [ ] 
- [x] **Questions -**
- [x] - **When I put in a type of capital, whose capital do we put in the index**
- [x] - **I do not have any input or metric. Then should I put it as blank or None**
- [x] - **How to put in irrelevant information or not required information in the different columns**
- [x] - **Elements of Capital have an associated Lifetime. Does this mean that the elements in the Lifetime variable of designs dataset should be put in the indices table**

## On line 393, re the *results* dataset

- [x] ISSUE WITH MAKING RESULTS
- [x] **What is mandatory what is not? I HAVE some ISSUEs while making the Results dataset. 
- [x] Are the cost,outputs, metrics mandatory**
- [x] ** I am unable to understand how to fill up the index column for the different variable types. I have never described an index for cost, nor for output, neither for metric. Although I do know what metrics I defined in my technology model. **

## Section to add: Modeling in Tyche
* RJH: Before we implement this, let's review our [Technology Model Example](https://nrel.github.io/tyche-docs/example-technology.html) section to see if we can expand it to fit this need. Not all of the datasets are discussed there, but they could be.
* Assign to: @rjhanes 

Example case study 1- Consider a PV system. It consists of a set of PV modules that convert sunlight into direct current power, an inverter that transforms the dc of the PV module into ac for the power line, and all the supporting infrastructure and installation costs.  This system We will also use this example to explain this tutorial.  This is a typical example which showcases Tyche usage. 

The technology model describes a process physically and economically (A classic but simple and generalized Techno-economic analysis) 

   * Converts inputs to outputs based on user defined technology model and ad-hoc parameters. 
   * The user defined model can integrate uncertainty in the input variables and parameters in the form of distribution. (For example, triangular distributions can be put as inputs for parameters or variables to incorporate uncertainty)
   * Requirement and data location for technology model is explained in Table 1. 

DESCRIBE the PV or other system here in detail and how to modify it to fit the user’s needs.  This should be a large section to include the description of all the steps needed….   

## Section to add: Jupyter Technology Analysis Notebook
Assign to: @rjhanes 

RJH: I think this will be difficult to understand unless we first walk through what the technology model is and what the input datasets cover. We can discuss at a high level what goes on in the analysis notebooks, but specifics will be difficult without the context.

- Describe Jupyter model and what it does: *The Jupyter notebooks are used once a technology model and input datasets have been developed. The notebook provides a convenient interface to the analysis methods built into the Tyche codebase, and can be used for ensemble evaluations, optimization studies, visualization, and exploratory analyses.*
- Describe Python model and what it does, bringing up to here the discussion from below: *The technology model itself is implemented in Python and consists of a set of methods (functions) to calculate a technology's capital costs, output amount(s), and metrics of interest.*
- Then describe the supporting data sets below

## Section to add: To begin the quick start guide, it needs to explain what Tyche is, what it does, and why this is of value to the user. Expand this to a full explanation
* RJH: I strongly suggest we leave this discussion on the main page of the documentation, where it is currently. We cannot make this "cheat sheet" completely standalone and have it remain a "cheat sheet" instead of the entire documentation.

## Wording change: "Module" to "Model" in *functions* dataset
Assign to: @rjhanes 
* See issue #88 and PR #108 . Anywhere there's a *functions* dataset example or discussion of the column names, update "Module" to "Model". That way, anytime we say "technology model", we're always referring to the .py file with the capital cost, etc methods.
* Since this is a pretty minor change but could involve multiple source files, I'll do this after other revisions have been merged together but before the next version is deployed.

## Add to installation instructions

* Tyche isn't supported on Linux systems (nor will it be)

**Comment by SamBaldwinDOE** [comment]
Rebecca:

Many thanks for all your work on this.  I look forward to talking on
Wednesday.

All the best,

sam

**Comment by TJTapajyoti** [comment]
Thank you for arranging all this nicely

**Comment by TJTapajyoti** [comment]
@rjhanes  Hi Rebecca, I have completed my edits of the Cheat sheet. I was able to successfully address all the issues that may arise where building a model from scratch and I added some minor nuances of building the datasets. I have one remaining doubt. That is filling up the Investment column in the Investment dataset. I think the current description in the table is not super clear about what to put in the column. The tranches and categories are fine. But the investment column description seems a bit odd. I have put in a small paragraph after the investment dataset discussion with a bold heading Relationship between Designs, Parameters, Tranches and Investment. 

In this paragraph,  I was thinking of writing this line - A scenario has a one -to- one relationship with a Tranche. I am wondering if this is true? Also linking Tranche to the Investment column, can we add a better description to fill in the Investment column info? 

I think the category column description is fine although its not really clear that a single category can extend over multiplte tranches.

**Comment by rjhanes** [comment]
The Scenario/Tranche/Investment relationship is pretty flexible. I think the intended (but not required) use case is for a Scenario to consist of multiple Tranches that each define the investment level in a Category, and for Scenarios to be defined based on intended outcome (ie Fast Progress, Slow Progress). An Investment is also intended to be a grouping of Tranches but is defined based on the dollar amount investment (ie No R&D Investment, Moderate R&D Investment). Having these two ways of grouping Tranches lets us quickly do a couple different kinds of analyses without resorting to optimization. However, as you point out a Scenario or an Investment can also be defined to consist of just one Tranche (investment into just one Category), which I'm pretty sure will be much less common when we're applying Tyche to IRL applications. How Scenarios and Investments are defined will be determined as part of the decision context specification, with input from the decision maker; I think it's also likely that Scenario and Investment definitions will be heavily iterated upon in real applications.

I'm not sure what you mean by "a single Category can extend over multiple Tranches" - a Tranche is a unit of investment, and so one Category (category = research area) can have several Tranche options such as Low, Medium, and High Investment. The important thing is that Tranches for a single Category are mutually exclusive: it's not possible to have both Low and Medium investment levels into a Category. Tranches can be combined across multiple Categories to construct Scenarios and Investments.

Once your edits are wrapped up, create a PR back into `doc-updates-fy23q1` and request my review. Once it's ready I'll also update Sam's doc branch with these revisions.

**Comment by rjhanes** [comment]
Closed for FY23 Q1 updates to the cheat sheet - see issue #107 for more general updates
